name: Build and Test Cookbook App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_unit_tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM Dependencies
      run: npm install
    - name: Start the Application
      run: npm run start &
    - name: Run the unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "ivano0ov_ivan"

  run_ui_tests:
    needs: build_and_unit_tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM dependecies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Start the application
      run: npm run start &
    - name: Run the ui tests
      run: npm run test:ui

  deploy_production:
    runs-on: ubuntu-latest
    needs: run_ui_tests
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}